// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package out

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ImageServiceClient is the client API for ImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageServiceClient interface {
	DownloadImages(ctx context.Context, opts ...grpc.CallOption) (ImageService_DownloadImagesClient, error)
}

type imageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageServiceClient(cc grpc.ClientConnInterface) ImageServiceClient {
	return &imageServiceClient{cc}
}

func (c *imageServiceClient) DownloadImages(ctx context.Context, opts ...grpc.CallOption) (ImageService_DownloadImagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ImageService_serviceDesc.Streams[0], "/main.ImageService/DownloadImages", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageServiceDownloadImagesClient{stream}
	return x, nil
}

type ImageService_DownloadImagesClient interface {
	Send(*DownloadImagesRequest) error
	CloseAndRecv() (*DownloadImagesResponse, error)
	grpc.ClientStream
}

type imageServiceDownloadImagesClient struct {
	grpc.ClientStream
}

func (x *imageServiceDownloadImagesClient) Send(m *DownloadImagesRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *imageServiceDownloadImagesClient) CloseAndRecv() (*DownloadImagesResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(DownloadImagesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ImageServiceServer is the server API for ImageService service.
// All implementations must embed UnimplementedImageServiceServer
// for forward compatibility
type ImageServiceServer interface {
	DownloadImages(ImageService_DownloadImagesServer) error
	mustEmbedUnimplementedImageServiceServer()
}

// UnimplementedImageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedImageServiceServer struct {
}

func (*UnimplementedImageServiceServer) DownloadImages(ImageService_DownloadImagesServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadImages not implemented")
}
func (*UnimplementedImageServiceServer) mustEmbedUnimplementedImageServiceServer() {}

func RegisterImageServiceServer(s *grpc.Server, srv ImageServiceServer) {
	s.RegisterService(&_ImageService_serviceDesc, srv)
}

func _ImageService_DownloadImages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImageServiceServer).DownloadImages(&imageServiceDownloadImagesServer{stream})
}

type ImageService_DownloadImagesServer interface {
	SendAndClose(*DownloadImagesResponse) error
	Recv() (*DownloadImagesRequest, error)
	grpc.ServerStream
}

type imageServiceDownloadImagesServer struct {
	grpc.ServerStream
}

func (x *imageServiceDownloadImagesServer) SendAndClose(m *DownloadImagesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *imageServiceDownloadImagesServer) Recv() (*DownloadImagesRequest, error) {
	m := new(DownloadImagesRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ImageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.ImageService",
	HandlerType: (*ImageServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadImages",
			Handler:       _ImageService_DownloadImages_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "image.proto",
}
